# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
cache: packages

matrix:
  include:
  - r: 3.4
  - r: oldrel
  - r: release
    r_packages:
    - covr
    - pkgdown
    after_success:
    - Rscript -e "covr::codecov()"
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: devel
  - r: release
    os: osx
addons:
  apt:
    packages:
      - devscripts
notifications:
  email:
    on_success: change
    on_failure: change
r_github_packages:
  - rstub/swephRdata
