# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
r:
  - 3.4
  - release
  - devel
matrix:
  exclude:
  - r: 3.4
    os: osx
  - r: devel
    os: osx
notifications:
  email:
    on_success: change
    on_failure: change
r_packages:
  - covr
repos:
  CRAN: https://cloud.r-project.org
  rstub: http://rstub.github.io/drat
after_success:
- test "$TRAVIS_R_VERSION_STRING" = "release" && Rscript -e 'covr::codecov()' || true
